### ISSUE TITLE
Full message is not included in data sent to graylog

### ISSUE THREAD

**Issue by michaelwiles** [rkcpi/logback-gelf-appender#11]
The read me about layout says 

> The Layout to use to format the LogEvent; the resulting string will be used as GELF's short_message (exception stacktraces are not included in this message)

Problem is the full message is not sent (It is only sent if fullstack trace is on and there is an exception).

I would like the full message to always be sent...

It's a fairly trivial change

**Comment by rkcpi** [comment]
Fixed in 1.3, thanks again!
