### ISSUE TITLE
Host name is resolved once for each log message

### ISSUE THREAD

**Issue by agrove-rms** [rkcpi/logback-gelf-appender#19]
If the host name is not supplied then the host name is resolved once per log message, which is an expensive syscall. This PR changes the behavior to resolve the host name once before the appender starts. This increased throughput by 15% for my benchmarks.

https://github.com/rkcpi/logback-gelf-appender/pull/18

**Comment by rkcpi** [comment]
Hi @agrove-rms, I just merged your PR. Closing this issue now. Thanks again!

Will do a new release shortly.
