### ISSUE TITLE
question: possible to tell programatically whether communication to graylog is working?

### ISSUE THREAD

**Issue by cortextual** [rkcpi/logback-gelf-appender#2]
I would love to be able to check (in code) whether communication with the graylog server is working. I could then add that check to a series of other status checks I use for a status URL. Then the load balancer and system monitoring tools can tell whether logging with GELF isn't working.

I've looked through the current source code and also the source code for org.graylog2:gelfclient:1.3.1, but so far haven't seen anything that might help.

**Comment by fabianbuch** [comment]
Usually logging is not the main business of your application, so I'd discourage making your load balancer aware of your logging status. For most applications it's more important to keep working even if logging is not working.

If you want to be notified if your logs are in graylog you might want tell your monitoring tools to have a look in graylog regulary. Additionally it's good practice to have fallback appenders that don't log via network, e. g. in local files on disk.

**Comment by cortextual** [comment]
Thanks
