### ISSUE TITLE
Unable to set different layout

### ISSUE THREAD

**Issue by augi** [rkcpi/logback-gelf-appender#4]
I'm using your appender and it works very well. Now, I would like to truncate very long messages so I would like to set a custom `layout`. The README says it's possible to set it but I'm not able to make it working :(

```xml
<appender name="GRAYLOG" class="de.appelgriepsch.logback.GelfAppender">
        <server>my-server</server>
        <port>12201</port>
        <protocol>UDP</protocol>
        <includeLevelName>true</includeLevelName>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%.255msg</pattern>
        </layout>
</appender>
```

Could you please update the README to contain how to setup custom `layout` correctly? It would be very useful for me. Thanks!

**Comment by augi** [comment]
Hi, will you have time to fix the documentation in the near future, please? Thanks!

**Comment by rkcpi** [comment]
I plan to have a look at this on the weekend. Sorry for the delay.

**Comment by rkcpi** [comment]
Turns out the readme documented a feature that was not yet implemented. I implemented setting the layout today and made a new release.

@augi using release 1.2.1 setting the layout should work as shown in your example configuration above. Thanks for reporting this!

**Comment by augi** [comment]
Cool! Thank you very much! :-)
